In [32]:
import pandas as pd
import numpy as np
import re

In [33]:
flats = pd.read_csv('flats_cleaned.csv')
houses = pd.read_csv('house_cleaned.csv')

In [34]:
flats.head(2)

,property_name,society,price,sector,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,...,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,area
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,krishna colony,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,...,4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746,900.0
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,ashok vihar,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,...,1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564,650.0

In [35]:
houses.head(2)

,property_name,property_type,society,price,price_per_sqft,area_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN

In [36]:
flats.rename(columns={'area':'area_sqft'},inplace = True)

In [37]:
flats.insert(loc=1,column='property_type',value='flat')

In [38]:
df = pd.concat([flats,houses],ignore_index = True)

In [39]:
df = df.sample(df.shape[0],ignore_index = True)

In [40]:
df.head(2)

,property_name,property_type,society,price,sector,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,...,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,area_sqft
0,3 Bedroom House for sale in Sector 33 Gurgaon,house,nitin vihar,0.85,NaN,9444.0,Plot area 900(83.61 sq.m.),3,2,0,...,1.0,West,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Airforce Hospital', 'S...",Independent house available for sale in nitin ...,NaN,"['High Ceiling Height', 'Water Storage', 'No o...","['Environment3 out of 5', 'Lifestyle4 out of 5...",NaN,900.0
1,2 BHK Flat in Ashok Vihar Phase 2,flat,shyam sadan,0.55,ashok vihar phase 2,6470.0,Carpet area: 700 (65.03 sq.m.),2,2,1,...,4.0,West,1 to 5 Year Old,"['Sheetla Mata Mandir', 'Chintapurni Mandir', ...",One of the best locations in gurugram as gurga...,"['2 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Security / Fire Alarm', 'Lift(s)', 'Water pu...","['Environment3 out of 5', 'Safety4 out of 5', ...",B68487870,850.0

In [41]:
df.shape

(3961, 22)

In [ ]:
df.drop(col)